//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qp_Firebase_ClickLog_Tables
    {
        public int Id { get; set; }
        public Nullable<int> RefId { get; set; }
        public string Token { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
