//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RobiSDPContext : DbContext
    {
        public RobiSDPContext()
            : base("name=RobiSDPContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int spInsertSubscriptionQ_To_SDP_channelID_1(string userID, string serviceId, string productID, string updateDesc)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            var serviceIdParameter = serviceId != null ?
                new ObjectParameter("serviceId", serviceId) :
                new ObjectParameter("serviceId", typeof(string));
    
            var productIDParameter = productID != null ?
                new ObjectParameter("productID", productID) :
                new ObjectParameter("productID", typeof(string));
    
            var updateDescParameter = updateDesc != null ?
                new ObjectParameter("updateDesc", updateDesc) :
                new ObjectParameter("updateDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertSubscriptionQ_To_SDP_channelID_1", userIDParameter, serviceIdParameter, productIDParameter, updateDescParameter);
        }
    }
}
