//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuizPlay_Played_Theme
    {
        public int ID { get; set; }
        public string MSISDN { get; set; }
        public Nullable<int> Theme { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
