//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LiveChallenge_Log
    {
        public long Id { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string FbIdSender { get; set; }
        public string FbIdReceiver { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsAccepted { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<System.DateTime> AcceptedTime { get; set; }
    }
}
