//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuizPlay_Access_Log
    {
        public int ID { get; set; }
        public string SOURCE_URL { get; set; }
        public string SERVICE_REQUEST { get; set; }
        public string MSISDN { get; set; }
        public string HS_MANUFACTURER { get; set; }
        public string HS_MODEL { get; set; }
        public string HS_DIM { get; set; }
        public string APN { get; set; }
        public string PORTAL_FULLnSHORT { get; set; }
        public string CMPAIN_KEY { get; set; }
        public Nullable<System.DateTime> TIME_STAMP { get; set; }
        public string IP { get; set; }
        public string OS { get; set; }
        public string UAHeader { get; set; }
    }
}
