//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuizPlayDateThemeRelation
    {
        public long ID { get; set; }
        public long ThemeID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tbl_QuizPlayTheme tbl_QuizPlayTheme { get; set; }
    }
}
