//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuizPlayQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_QuizPlayQuestions()
        {
            this.tbl_QuizPlayUserAnswerBonusHour = new HashSet<tbl_QuizPlayUserAnswerBonusHour>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> QuestionNo { get; set; }
        public long QuestionThemeID { get; set; }
        public string Ques_level { get; set; }
        public string QuestionImage { get; set; }
        public string Question { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Answer { get; set; }
        public bool IsActive { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_QuizPlayUserAnswerBonusHour> tbl_QuizPlayUserAnswerBonusHour { get; set; }
    }
}
