//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QPFbInfo
    {
        public long Id { get; set; }
        public string MSISDN { get; set; }
        public string FbId { get; set; }
        public string FbName { get; set; }
        public string FbImageUrl { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
