//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuizPlay_Live_MagicHour
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Hour { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string CreatedBy { get; set; }
        public string DayPart { get; set; }
    }
}
