//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuizPlay_MyAccount
    {
        public int ID { get; set; }
        public string MSISDN { get; set; }
        public string Content { get; set; }
        public string Charge { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
