//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizPlayNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuizPlayResultBonusHour
    {
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public string MSISDN { get; set; }
        public long SessionNumber { get; set; }
        public int TotalRight { get; set; }
        public long TimeTaken { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
