//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QuizPlayNew.HSP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HansetDetectionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::QuizPlayNew.Properties.Settings.Default.QuizPlayNew_HSP_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HansetDetectionCompletedEventHandler HansetDetectionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HansetDetection", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Profiling HansetDetection(string UserAgent, string UserXML) {
            object[] results = this.Invoke("HansetDetection", new object[] {
                        UserAgent,
                        UserXML});
            return ((Profiling)(results[0]));
        }
        
        /// <remarks/>
        public void HansetDetectionAsync(string UserAgent, string UserXML) {
            this.HansetDetectionAsync(UserAgent, UserXML, null);
        }
        
        /// <remarks/>
        public void HansetDetectionAsync(string UserAgent, string UserXML, object userState) {
            if ((this.HansetDetectionOperationCompleted == null)) {
                this.HansetDetectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHansetDetectionOperationCompleted);
            }
            this.InvokeAsync("HansetDetection", new object[] {
                        UserAgent,
                        UserXML}, this.HansetDetectionOperationCompleted, userState);
        }
        
        private void OnHansetDetectionOperationCompleted(object arg) {
            if ((this.HansetDetectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HansetDetectionCompleted(this, new HansetDetectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Profiling {
        
        private string manufacturerField;
        
        private string modelField;
        
        private string dimensionField;
        
        private string osField;
        
        private string isTabletField;
        
        private string uAXMLField;
        
        private string is_botField;
        
        private string marketing_nameField;
        
        private string full_device_nameField;
        
        /// <remarks/>
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Dimension {
            get {
                return this.dimensionField;
            }
            set {
                this.dimensionField = value;
            }
        }
        
        /// <remarks/>
        public string OS {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
            }
        }
        
        /// <remarks/>
        public string isTablet {
            get {
                return this.isTabletField;
            }
            set {
                this.isTabletField = value;
            }
        }
        
        /// <remarks/>
        public string UAXML {
            get {
                return this.uAXMLField;
            }
            set {
                this.uAXMLField = value;
            }
        }
        
        /// <remarks/>
        public string is_bot {
            get {
                return this.is_botField;
            }
            set {
                this.is_botField = value;
            }
        }
        
        /// <remarks/>
        public string marketing_name {
            get {
                return this.marketing_nameField;
            }
            set {
                this.marketing_nameField = value;
            }
        }
        
        /// <remarks/>
        public string full_device_name {
            get {
                return this.full_device_nameField;
            }
            set {
                this.full_device_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void HansetDetectionCompletedEventHandler(object sender, HansetDetectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HansetDetectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HansetDetectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Profiling Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Profiling)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591